//
//  UserListModels.swift
//  CleanSwift
//
//  Created by Josep Escobar on 30/06/2019.
//  Copyright (c) 2019 Josep Escobar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum UserList {
    // MARK: Use cases

    enum LoadData {
        struct Request {
        }
        struct Response {
            let users: [User]
        }
        struct ViewModel {

            let users: [User]
            
            /// Returns number of users can be returned
            ///
            /// - Returns: Number of users
            func getNumberOfUsers() -> Int {
                return users.count
            }
            
            /// Format User name with First name and Last name
            ///
            /// - Parameter index: Index from User array
            /// - Returns: returns formated value, never returns nil
            func getfullUserName(index: Int) -> String {
                guard let firstName = users[index].name?.first,
                      let lastName = users[index].name?.last else {
                        return "No name"
                }
                return "\(firstName) \(lastName)"
            }
            
            /// Get avatar URL
            ///
            /// - Parameter index: Index from User array
            /// - Returns: returns URL in String format, never returns nil
            func getAvatarImage(index: Int) -> String {
                guard let avatarUrl = users[index].picture?.medium else {
                    return ""
                }
                return avatarUrl
            }
        }
    }
}
