//
//  UserListViewController.swift
//  CleanSwift
//
//  Created by Josep Escobar on 30/06/2019.
//  Copyright (c) 2019 Josep Escobar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserListDisplayLogic: class {
    func displayInitialData(viewModel: UserList.LoadData.ViewModel)
    func displayUserDetail(viewModel: UserList.UserDetail.ViewModel)
}

class UserListViewController: UIViewController, UserListDisplayLogic {
    var interactor: UserListBusinessLogic?
    var router: (NSObjectProtocol & UserListRoutingLogic & UserListDataPassing)?
    var viewModel = UserList.LoadData.ViewModel(users: [])

    @IBOutlet weak var tableView: UITableView!

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = UserListInteractor()
        let presenter = UserListPresenter()
        let router = UserListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        configureUI()
        loadInitialData()
    }

    // MARK: Do something

    func configureUI() {
        tableView.delegate = self
        tableView.dataSource = self
        tableView.estimatedRowHeight = 90
        tableView.rowHeight = UITableView.automaticDimension
        title = "Users"
    }

    func loadInitialData() {
        let request = UserList.LoadData.Request()
        interactor?.doLoadInitialData(request: request)
    }

    func displayInitialData(viewModel: UserList.LoadData.ViewModel) {
        self.viewModel = viewModel
        tableView.reloadData()
    }
    
    func displayUserDetail(viewModel: UserList.UserDetail.ViewModel) {
        router?.routeToDetail()
    }
}

extension UserListViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let user = viewModel.users[indexPath.row]
        let request = UserList.UserDetail.Request(user: user)
        interactor?.doLoadUserDetail(request: request)
    }
}

extension UserListViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return viewModel.getNumberOfUsers()
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if let cell = tableView.dequeueReusableCell(withIdentifier: "UserListCell", for: indexPath) as? UserListTableViewCell {
            cell.setupCell(name: viewModel.getfullUserName(index: indexPath.row),
                           avatarUrl: viewModel.getAvatarImage(index: indexPath.row),
                           email: viewModel.getEmail(index: indexPath.row),
                           phone: viewModel.getPhone(index: indexPath.row))
            return cell
        } else {
            return UITableViewCell()
        }
    }

}
