//
//  UserListPresenter.swift
//  CleanSwift
//
//  Created by Josep Escobar on 30/06/2019.
//  Copyright (c) 2019 Josep Escobar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserListPresentationLogic {
  func presentSomething(response: UserList.Something.Response)
}

class UserListPresenter: UserListPresentationLogic {
  weak var viewController: UserListDisplayLogic?

  // MARK: Do something

  func presentSomething(response: UserList.Something.Response) {
    let viewModel = UserList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
