//
//  UserListModels.swift
//  CleanSwift
//
//  Created by Josep Escobar on 30/06/2019.
//  Copyright (c) 2019 Josep Escobar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum UserList {
    // MARK: Use cases

    enum LoadData {
        struct Request {
        }
        struct Response {
            let users: [User]
        }
        struct ViewModel {
            // Todo: Return only needed data and formated
            let users: [User]
        }
    }
}
