//
//  UserListInteractor.swift
//  CleanSwift
//
//  Created by Josep Escobar on 30/06/2019.
//  Copyright (c) 2019 Josep Escobar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserListBusinessLogic {
  func doSomething(request: UserList.Something.Request)
}

protocol UserListDataStore {
  //var name: String { get set }
}

class UserListInteractor: UserListBusinessLogic, UserListDataStore {
  var presenter: UserListPresentationLogic?
  var worker: UserListWorker?
  //var name: String = ""

  // MARK: Do something

  func doSomething(request: UserList.Something.Request) {
    worker = UserListWorker()
    worker?.doSomeWork()

    let response = UserList.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
