//
//  UserListInteractor.swift
//  CleanSwift
//
//  Created by Josep Escobar on 30/06/2019.
//  Copyright (c) 2019 Josep Escobar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserListBusinessLogic {
    func doLoadInitialData(request: UserList.LoadData.Request)
}

protocol UserListDataStore {
    //var name: String { get set }
}

class UserListInteractor: UserListBusinessLogic, UserListDataStore {
    var presenter: UserListPresentationLogic?
    var worker: UserListWorker?
    //var name: String = ""

    // MARK: Do something

    func doLoadInitialData(request: UserList.LoadData.Request) {
        worker = UserListWorker()
        worker?.fetchUsers(completionHandler: { users in
            let response = UserList.LoadData.Response(users: users)
            self.presenter?.presentInitialData(response: response)
        })

    }
}
