//
//  UserDetailInteractor.swift
//  CleanSwift
//
//  Created by Josep Escobar on 30/06/2019.
//  Copyright (c) 2019 Josep Escobar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserDetailBusinessLogic
{
  func doSomething(request: UserDetail.Something.Request)
}

protocol UserDetailDataStore
{
  //var name: String { get set }
}

class UserDetailInteractor: UserDetailBusinessLogic, UserDetailDataStore
{
  var presenter: UserDetailPresentationLogic?
  var worker: UserDetailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: UserDetail.Something.Request)
  {
    worker = UserDetailWorker()
    worker?.doSomeWork()
    
    let response = UserDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
